/**
 * DittoFrame — iframe wrapper that embeds the Ditto demo client (Story D9,
 * AC-D9-2 / AC-D9-6).
 *
 * The Ditto build artifact lives at `packages/hub-web/public/ditto/`
 * and is served at `/ditto/` by Vite (which exposes `public/` at the
 * root in both dev and build). The artifact is generated by
 * `scripts/prep-ditto-build.sh`. **If the build hasn't been run yet, the
 * iframe will 404** — that's expected on a fresh checkout. Run the prep
 * script to populate it; the dashboard layout works either way.
 *
 * Sandboxing: same-origin (we serve it ourselves), but Ditto is a
 * client-side Capacitor/Radix SPA that signs Nostr events in JS and
 * opens WebSockets. The minimum sandbox tokens we need:
 *   - `allow-scripts` — Ditto is JS-driven; without this nothing renders.
 *   - `allow-same-origin` — required so Ditto's IndexedDB/localStorage
 *     state survives reloads and so client-side fetch to its own origin
 *     works (the bundled fonts load via same-origin requests).
 *   - `allow-forms` — login/compose flows post forms.
 *   - `allow-popups` — Ditto opens external links (e.g. block-explorer)
 *     in new tabs; without this, target=_blank is silently dropped.
 * WebSockets do not require a sandbox token. We do **not** include
 * `allow-top-navigation` — Ditto must not be able to redirect the
 * dashboard.
 */

import * as React from 'react';
import { cn } from '@/lib/utils';

export interface DittoFrameProps {
  /** Override the iframe src (test injection). Defaults to `/ditto/`. */
  src?: string;
  className?: string;
}

const DEFAULT_SRC = '/ditto/';
const SANDBOX = 'allow-scripts allow-same-origin allow-forms allow-popups';

export function DittoFrame({ src = DEFAULT_SRC, className }: DittoFrameProps) {
  return (
    <iframe
      src={src}
      title="Ditto demo client"
      // Keep the iframe filling its parent — DemoGrid's left section
      // gives it the column's full height/width; min-h-0 on the parent
      // section is what allows this to behave on a 1440x900 viewport.
      className={cn(
        'shadow-border h-full w-full rounded-lg bg-canvas',
        className
      )}
      // See the file header for sandbox rationale.
      sandbox={SANDBOX}
      // Performance hint: Ditto isn't critical-path for first paint of
      // the dashboard (the right column is what builds operator
      // credibility). Loading lazily lets the right-column SSE connect
      // first.
      loading="lazy"
      // referrerPolicy: don't leak the dashboard URL to Ditto's outbound
      // probes. Same-origin still works.
      referrerPolicy="no-referrer"
    />
  );
}

DittoFrame.displayName = 'DittoFrame';
