/**
 * HS node-env writer for `hub hs up`.
 *
 * Writes `~/.hub/compose/.env` from the operator's `network` mode so the
 * HS compose template's `${EVM_CHAIN:-}` / `${EVM_RPC_URL:-}` / `${SOLANA_*:-}`
 * interpolations resolve to the real public endpoints for the chosen tier — the
 * same network profile the apex connector (hs-config-writer) and the per-node
 * overlay (nodes-lifecycle `buildNetworkNodeEnv`) consume.
 *
 * Docker Compose auto-loads a `.env` from the project directory, which defaults
 * to the directory of the first `-f` compose file — here
 * `~/.hub/compose/hub-hs.yml` — so the file MUST live in `compose/`.
 *
 * Without this file the node env vars were never set, so the town node fell back
 * to the local `anvil` preset (`localhost:8545`, unreachable in the HS network)
 * and boot-looped on "JsonRpcProvider failed to detect network", never dialing
 * the connector → permanently "disconnected".
 */

import {
  writeFileSync,
  chmodSync,
  lstatSync,
  statSync,
  mkdirSync,
  existsSync,
} from 'node:fs';
import { join } from 'node:path';
import { resolveConfigNetworkProfile } from '../config/network-profile.js';
import type { HubConfig } from '../config/schema.js';

/** Result of {@link writeHsNodeEnvFile}. */
export interface WriteHsNodeEnvResult {
  envPath: string;
  /** The env keys written (excludes empty values). */
  keys: string[];
}

/**
 * Write `<configDir>/compose/.env` from the config's network mode.
 *
 * @param configDir - The Hub home (dir containing config.yaml). The file
 *   is written to the `compose/` subdir so Compose auto-discovers it.
 * @param config - The Hub config (reads `network` + `chainProviders`).
 */
export function writeHsNodeEnvFile(
  configDir: string,
  config: HubConfig
): WriteHsNodeEnvResult {
  const composeDir = join(configDir, 'compose');
  const envPath = join(composeDir, '.env');

  const profile = resolveConfigNetworkProfile(config);

  // Serialize only keys with real values (absent ⇒ compose `${VAR:-}` default).
  const lines: string[] = [
    '# Generated by `hub hs up` from the `network` mode — do not edit.',
    `# network=${profile.network}`,
  ];
  const keys: string[] = [];
  for (const [key, value] of Object.entries(profile.nodeEnv)) {
    if (value !== undefined && value !== '') {
      lines.push(`${key}=${value}`);
      keys.push(key);
    }
  }

  // materializeComposeTemplate normally creates compose/ (0o700) before this
  // runs, but create it defensively so the writer is self-sufficient (e.g. when
  // materialize is mocked). Refuse to follow a symlinked dir we did not create
  // (mirrors compose-loader's guard).
  if (existsSync(composeDir)) {
    const lst = lstatSync(composeDir);
    if (lst.isSymbolicLink() && !statSync(composeDir).isDirectory()) {
      throw new Error(
        `${composeDir} is a symlink to a non-directory; refusing to write .env.`
      );
    }
  } else {
    mkdirSync(composeDir, { recursive: true, mode: 0o700 });
  }

  writeFileSync(envPath, lines.join('\n') + '\n', { mode: 0o600 });
  // Tighten in case the file pre-existed with a broader mode.
  chmodSync(envPath, 0o600);

  return { envPath, keys };
}
