/**
 * Connector types for Hub (Story 21.3).
 *
 * Defines the runtime configuration shape for the standalone ILP connector,
 * peer entries, and admin API response types.
 */

import type { NodeType } from '../docker/types.js';

/**
 * A peer entry representing a child node connected to the connector via BTP.
 * Each active node becomes a child peer of the connector.
 */
export interface PeerEntry {
  /** Node type identifier (e.g., 'town', 'mill', 'dvm') */
  id: string;
  /** Relationship to connector — nodes are always children */
  relation: 'child';
  /** BTP WebSocket URL for Docker-internal communication */
  btpUrl: string;
  /** Asset code for ILP packets (e.g., 'USD') */
  assetCode: string;
  /** Asset scale (e.g., 6 for micro-units) */
  assetScale: number;
}

/**
/**
 * Hidden-service configuration for the connector's inbound BTP path.
 *
 * When set under transport.hiddenService, the connector boots the
 * `@anyone-protocol/anyone-client` SDK in-process (Story 35.5 of the
 * connector repo, "ManagedAnonClient") which spawns the `anon` binary
 * and publishes a v3 hidden service. The .anyone hostname is read from
 * `${dir}/hostname` after publish and substituted into the connector's
 * externalUrl as `wss://<hostname>.anyone/btp`.
 *
 * Operator surface lives at transport.hiddenService.{dir, port}; the
 * connector's wire format is more verbose (transport.managedOptions.*) —
 * config-generator handles the translation.
 *
 * Per-hub-instance keypair: the secret key under `${dir}/` is the
 * .anyone identity. Persist it across redeploys to keep the address stable;
 * delete it to rotate.
 */
export interface HiddenServiceConfig {
  /**
   * Absolute path to the v3 hidden-service key directory inside the
   * connector container. The connector creates `hs_ed25519_secret_key`,
   * `hs_ed25519_public_key`, and `hostname` here on first boot, then
   * reuses them on subsequent boots if present.
   */
  dir: string;
  /**
   * Hidden service port advertised on the .anyone address. Forwards to
   * the connector's BTP server (typically same port as connector's
   * btpServerPort, since the HS port = the port external peers dial).
   */
  port: number;
  /**
   * Optional override for the externalUrl the connector advertises.
   * Defaults to the literal "auto" when unset, which makes the connector
   * resolve the .anyone hostname from `${dir}/hostname` at startup.
   * Set explicitly only when forcing a specific .anyone address (rare).
   */
  externalUrl?: string;
  /** Overall deadline for SOCKS port readiness (ms). Default 60000. */
  startupTimeoutMs?: number;
  /** Overall deadline for `sdk.stop()` (ms). Default 10000. */
  stopTimeoutMs?: number;
}

/**
 * Runtime configuration for the standalone ILP connector.
 * Generated by ConnectorConfigGenerator from HubConfig.
 */
export interface ConnectorRuntimeConfig {
  /** Admin API listen port */
  adminPort: number;
  /** Base ILP address for this connector */
  ilpAddress: string;
  /** List of child peer entries (one per active node) */
  peers: PeerEntry[];
  /** Transport configuration */
  transport: {
    /**
     * Operator-facing transport selection. Maps to the connector's
     * discriminated union internally (mode='hs' → type='socks5').
     */
    mode: 'hs' | 'direct';
    /** SOCKS5 proxy URL (must be socks5h://) — required when mode='hs'. */
    socksProxy?: string;
    /**
     * Externally reachable BTP URL the connector advertises to peers.
     * Required when mode='hs' AND hiddenService is unset (operator runs
     * their own anon binary externally). Ignored for mode='direct'.
     * When hiddenService IS set and externalUrl is unset, the generator
     * emits the literal "auto" so the connector resolves the .anyone
     * hostname at startup.
     */
    externalUrl?: string;
    /** Inbound hidden-service publication (Story 35.5 path). */
    hiddenService?: HiddenServiceConfig;
  };
}

// ── Admin API response types ──
//
// These mirror the connector's served shapes verbatim — see
// @toon-protocol/connector packages/connector/src/http/types.ts (HealthStatus)
// and packages/connector/src/http/admin-api.ts (AdminMetricsJsonResponse,
// /admin/peers handler). Drift here means dashboards break silently; the
// stub canary in `connector/contract-canary.test.ts` ratchets these shapes,
// and the running-image canary in `__integration__/connector-image-contract.test.ts`
// asserts the real connector still serves them.

/**
 * Response from GET /health on the connector's healthCheckPort.
 * Mirrors `HealthStatus` from `@toon-protocol/connector`.
 */
export interface HealthResponse {
  status: 'healthy' | 'unhealthy' | 'starting' | 'degraded';
  uptime: number;
  peersConnected: number;
  totalPeers: number;
  timestamp: string;
  nodeId?: string;
  version?: string;
}

/**
 * Per-peer ILP counter snapshot from GET /admin/metrics.json.
 * Mirrors `AdminMetricsJsonPeer` from `@toon-protocol/connector`.
 */
export interface MetricsPeerEntry {
  peerId: string;
  connected: boolean;
  packetsForwarded: number;
  packetsRejected: number;
  bytesSent: number;
  /** Connector v3.7.0+ (toon-protocol/connector#73). Counts packets accepted
   *  via the self-delivery code path (route nextHop === connector's own
   *  nodeId). Older connectors omit this field — default to 0 at consumers. */
  packetsLocallyDelivered?: number;
  lastPacketAt: string | null;
}

/**
 * Response from GET /admin/metrics.json on the connector's adminApi port.
 * Mirrors `AdminMetricsJsonResponse` from `@toon-protocol/connector`.
 */
export interface MetricsResponse {
  uptimeSeconds: number;
  aggregate: {
    packetsForwarded: number;
    packetsRejected: number;
    bytesSent: number;
    /** Connector v3.7.0+ — see MetricsPeerEntry.packetsLocallyDelivered. */
    packetsLocallyDelivered?: number;
  };
  peers: MetricsPeerEntry[];
  timestamp: string;
}

/**
 * Peer entry from GET /admin/peers on the connector's adminApi port.
 * Mirrors the response of the connector's `router.get('/peers', …)` handler.
 * Note: per-peer packet counters live on /admin/metrics.json, not here.
 */
export interface PeerStatus {
  id: string;
  connected: boolean;
  ilpAddresses: string[];
  routeCount: number;
}

/**
 * Wrapper response from GET /admin/peers.
 * Mirrors the connector's `router.get('/peers')` JSON envelope.
 */
export interface PeersResponse {
  nodeId: string;
  peerCount: number;
  connectedCount: number;
  peers: PeerStatus[];
}

/**
 * Channel summary entry from GET /admin/channels on the connector's adminApi port.
 * Mirrors `ChannelSummary` from `@toon-protocol/connector`
 * (packages/connector/src/http/admin-api.ts ChannelSummary at v3.x).
 *
 * `status` is kept as `string` (not a union) because the connector's enum may
 * grow without warning — the contract canary catches shape drift, not enum domain.
 */
export interface ChannelSummary {
  channelId: string;
  peerId: string;
  chain: string;
  status: string;
  deposit: string;
  lastActivity: string;
}

/**
 * Filter params for GET /packets on the connector admin API.
 *
 * Hub-Side Contract (§getPacketLog) — added in story 21.10.
 * The connector must expose `GET /packets?ilpAddress=<>&since=<>&limit=<>`.
 * If the running connector image does not expose this endpoint, the
 * /nodes/:type/packets/timeseries route returns 503 and the contract canary
 * will catch the drift. See packages/sdk/CONNECTOR_MIGRATION.md §Hub-Side Contract.
 */
export interface PacketLogFilter {
  ilpAddress?: string;
  since?: number;
  limit?: number;
}

/** A single packet log entry returned by GET /packets */
export interface PacketLogEntry {
  ts: number;
  ilpAddressFrom: string;
  ilpAddressTo: string;
  amount: string;
  result: 'fulfill' | 'reject' | 'timeout';
}

/** Response shape for GET /packets (array of entries) */
export type PacketLogResponse = PacketLogEntry[];

/**
 * Response from GET /admin/hs-hostname on the connector's adminApi port.
 * Mirrors the connector v3.5.0+ `HsHostnameResponse` (Story 44.1 / AC FR35).
 * Both fields are null while the .anyone hidden-service bootstrap is in
 * progress; both become non-null once the descriptor is published.
 */
export interface HsHostnameResponse {
  hostname: string | null;
  publishedAt: string | null;
}

/** Node types that can be registered as peers */
export type { NodeType };

// ── Earnings response types (endpoint added in connector v3.2.0; consumed by Hub from v3.3.3+) ──
//
// Source of truth: @toon-protocol/connector
//   packages/connector/src/http/admin-api.ts (AdminEarnings* interfaces)
//
// These are re-declared here (NOT re-exported from @toon-protocol/connector)
// because the connector's public lib.ts exports settlement/channel/payment
// types only — AdminEarnings* types are intentionally absent from its public
// surface (connector CONNECTOR_RELEASE_CONTRACT.md §admin-API). Re-declaring
// mirrors the established pattern for HealthResponse, MetricsResponse,
// PeersResponse, HsHostnameResponse, and PacketLogEntry.
//
// The stub canary in `connector/contract-canary.test.ts` and the real-image
// canary in `__integration__/connector-image-contract.test.ts` assert that
// the connector still serves this shape at runtime.

/**
 * Per-asset earnings row from GET /admin/earnings.json (endpoint added in connector v3.2.0).
 * Mirrors `AdminEarningsByAsset` from `@toon-protocol/connector` admin-api.
 *
 * Cumulative amounts are decimal-string bigints (JSON-safe for any asset scale).
 * `claimsReceivedTotal` tracks value received from the peer (they paid us);
 * `claimsSentTotal` tracks value forwarded to the peer (they earned).
 */
export interface AssetEarnings {
  assetCode: string;
  assetScale: number;
  claimsReceivedTotal: string;
  claimsSentTotal: string;
  netBalance: string;
  lastClaimAt: string | null;
}

/**
 * Per-peer earnings entry from GET /admin/earnings.json.
 * Mirrors `AdminEarningsJsonPeer` from
 * `@toon-protocol/connector packages/connector/src/http/admin-api.ts:278-281`.
 */
export interface PeerEarnings {
  peerId: string;
  byAsset: AssetEarnings[];
}

/**
 * Connector fee rollup from GET /admin/earnings.json.
 * Mirrors `AdminEarningsConnectorFee` from
 * `@toon-protocol/connector packages/connector/src/http/admin-api.ts:283-287`.
 */
export interface ConnectorFeeEntry {
  assetCode: string;
  assetScale: number;
  total: string;
}

/**
 * A single recent claim entry from GET /admin/earnings.json.
 * Mirrors `AdminEarningsRecentClaim` from
 * `@toon-protocol/connector packages/connector/src/http/admin-api.ts:289-296`.
 */
export interface RecentClaim {
  peerId: string;
  assetCode: string;
  assetScale: number;
  amount: string;
  direction: 'inbound' | 'outbound';
  at: string;
}

/**
 * Typed wrapper around the connector's wire-level `timestamp: string` field.
 * The connector's `AdminEarningsJsonResponse` carries a plain ISO-8601 string
 * (`packages/connector/src/http/admin-api.ts:298-304`). Hub wraps it as
 * a value object so dashboard consumers have a typed handle and the field can
 * be extended (`epoch?`, `timezone?`) without breaking callers.
 *
 * `ConnectorAdminClient.getEarnings()` performs the wrap on the way out:
 * `timestamp: { iso: rawString }`.
 */
export interface EarningsTimestamp {
  iso: string;
}

/**
 * Response from GET /admin/earnings.json on the connector's adminApi port.
 * Mirrors `AdminEarningsJsonResponse` from
 * `@toon-protocol/connector packages/connector/src/http/admin-api.ts:298-304`.
 *
 * NOTE: The connector's wire shape carries `timestamp: string`. Hub's
 * `getEarnings()` adapts it to `timestamp: EarningsTimestamp` (value object).
 *
 * Returns HTTP 503 when the connector is started without settlement config
 * (accountManager / claimReceiver not wired). Hub's apex always wires
 * both; 503 in production indicates connector misconfiguration.
 */
export interface EarningsResponse {
  uptimeSeconds: number;
  peers: PeerEarnings[];
  connectorFees: ConnectorFeeEntry[];
  recentClaims: RecentClaim[];
  timestamp: EarningsTimestamp;
}
