#!/usr/bin/env node
/**
 * Townhouse Fastify API server for the dev:docker loop.
 * Env vars are pre-loaded by dotenv-cli from .env.townhouse-dev.
 * Starts the API on port 9400, pointed at TOWNHOUSE_CONNECTOR_ADMIN_URL.
 */

import Docker from 'dockerode';
import {
  getDefaultConfig,
  DockerOrchestrator,
  WalletManager,
  ConnectorAdminClient,
  TransportProbe,
  DEFAULT_ATOR_PROXY,
  createApiServer,
} from '@toon-protocol/townhouse';
import { homedir } from 'node:os';
import { join } from 'node:path';

const connectorAdminUrl =
  process.env['TOWNHOUSE_CONNECTOR_ADMIN_URL'] ?? 'http://127.0.0.1:28080';

const config = getDefaultConfig();

// Dev-loop convenience: until the first-run wizard (story 21.14) ships,
// flip the three node types to enabled so the Home view (story 21.9-lite)
// has cards to render instead of bouncing into the empty state. The
// underlying Docker orchestrator still reports the real container state —
// the dev stack uses different container names (`townhouse-dev-*`) so cards
// will surface as `down` until 21.14 wires the orchestrator to dev fixtures.
config.nodes.town = { ...config.nodes.town, enabled: true };
config.nodes.mill = { ...config.nodes.mill, enabled: true };
config.nodes.dvm = { ...config.nodes.dvm, enabled: true };

const docker = new Docker();
const orchestrator = new DockerOrchestrator(docker, config);

const walletPath =
  config.wallet.encrypted_path ?? join(homedir(), '.townhouse', 'wallet.enc');
const wallet = new WalletManager({ encryptedPath: walletPath });

// Dev-loop wallet auto-init: set TOWNHOUSE_DEV_WALLET_MNEMONIC in .env.townhouse-dev
// (generated by scripts/townhouse-dev-infra.sh up). NEVER set in production.
// Hard-pinned to BIP-39 test-vector-zero — any other value is rejected so a
// developer who pastes a real mnemonic by accident gets a loud error instead of
// silent address derivation + console logging. Operators who need a different
// mnemonic must use the production `townhouse init` (password-gated) flow.
const TEST_VECTOR_MNEMONIC =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';
const TEST_VECTOR_DEV_PASSWORD = 'townhouse-dev';
const devMnemonic = process.env['TOWNHOUSE_DEV_WALLET_MNEMONIC'];
if (devMnemonic && devMnemonic !== TEST_VECTOR_MNEMONIC) {
  console.error(
    '[Townhouse API] TOWNHOUSE_DEV_WALLET_MNEMONIC is set but does not match the BIP-39 test-vector-zero phrase.\n' +
      '                The dev loop refuses to start with a non-test-vector mnemonic to prevent\n' +
      '                accidental real-key derivation. If you need a different mnemonic, run\n' +
      '                `townhouse init` to enter the password-gated production flow.'
  );
  process.exit(1);
}
if (devMnemonic) {
  await wallet
    .fromMnemonic(devMnemonic)
    .then(async (state) => {
      const keys = state.keys;
      const truncate = (addr) =>
        addr ? `${addr.slice(0, 8)}…${addr.slice(-4)}` : '(none)';
      console.log(
        '[Townhouse API] dev wallet initialized from TOWNHOUSE_DEV_WALLET_MNEMONIC'
      );
      console.log(
        `[Townhouse API]   town EVM: ${truncate(keys.town.evmAddress)}`
      );
      console.log(
        `[Townhouse API]   mill EVM: ${truncate(keys.mill.evmAddress)}`
      );
      console.log(
        `[Townhouse API]   dvm  EVM: ${truncate(keys.dvm.evmAddress)}`
      );

      // Decision-1 patch: also write ~/.townhouse/wallet.enc so POST /wallet/reveal
      // is exercisable against the live dev stack. Encrypted with a documented dev
      // password (`townhouse-dev`). Only writes if the file is absent — never
      // overwrites an existing operator wallet.
      try {
        const { existsSync, mkdirSync, writeFileSync } =
          await import('node:fs');
        const { dirname } = await import('node:path');
        const { encryptWallet } = await import('@toon-protocol/townhouse');
        if (!existsSync(walletPath)) {
          mkdirSync(dirname(walletPath), { recursive: true });
          const encrypted = await encryptWallet(
            devMnemonic,
            TEST_VECTOR_DEV_PASSWORD
          );
          writeFileSync(walletPath, JSON.stringify(encrypted), 'utf8');
          console.log(
            `[Townhouse API] wallet.enc written to ${walletPath} (dev password: ${TEST_VECTOR_DEV_PASSWORD})`
          );
        }
      } catch (err) {
        console.warn(
          '[Townhouse API] could not write dev wallet.enc:',
          err.message
        );
      }
    })
    .catch((err) => {
      console.warn(
        '[Townhouse API] TOWNHOUSE_DEV_WALLET_MNEMONIC is set but wallet.fromMnemonic failed:',
        err.message
      );
    });
} else {
  console.warn(
    '[Townhouse API] TOWNHOUSE_DEV_WALLET_MNEMONIC not set — wallet routes will return 503'
  );
}

const connectorAdmin = new ConnectorAdminClient(connectorAdminUrl);

// `configPath` is the YAML config destination consumed by `nodes-patch` route's
// `saveConfig(deps.configPath, ...)`. Must NOT collide with `walletPath` — that
// would corrupt the encrypted wallet file on a `PATCH /api/nodes/:type`.
const configPath =
  process.env['TOWNHOUSE_CONFIG_PATH'] ??
  join(homedir(), '.townhouse', 'townhouse-dev.yaml');

// Transport probe — probes the dev SOCKS5 service (127.0.0.1:28050) when config
// is set to ATOR mode; silent in direct mode (the default).
const devSocksProxy =
  process.env['TOWNHOUSE_DEV_SOCKS_PROXY'] ?? 'socks5://127.0.0.1:28050';
const transportProbe = new TransportProbe({
  proxyUrl:
    config.transport.mode === 'ator'
      ? (config.transport.socksProxy ?? DEFAULT_ATOR_PROXY)
      : '',
});
if (config.transport.mode === 'ator') {
  transportProbe.start();
}
// Dev-only: ?transport=ator on GET /api/transport returns an ATOR-mode stub
// so designers can preview the green-ATOR-dot path without changing config.
const devTransportOverride = process.env['TOWNHOUSE_DEV_TRANSPORT'];

const apiDeps = {
  configPath,
  config,
  orchestrator,
  wallet,
  connectorAdmin,
  transportProbe,
};

const server = await createApiServer(apiDeps);

// Dev-only: intercept GET /api/transport to support ?transport=ator preview.
// This hook runs AFTER the route handler's schema validation but before the
// real handler. We use addHook on the raw server to override the response
// when the dev transport override query param is present.
server.app.addHook('onRequest', async (request, reply) => {
  if (request.method !== 'GET') return;
  let pathname;
  try {
    pathname = new URL(request.url, 'http://localhost').pathname;
  } catch {
    // Malformed URL — let Fastify handle it normally.
    return;
  }
  // Exact match — do NOT use startsWith, which would hijack future paths
  // like /api/transport-status or /api/transport2.
  if (pathname !== '/api/transport') return;
  const forced =
    new URL(request.url, 'http://localhost').searchParams.get('transport') ??
    devTransportOverride;
  if (!forced) return;
  const mode = forced === 'ator' ? 'ator' : 'direct';
  await reply.status(200).send({
    mode,
    ...(mode === 'ator' ? { socksProxy: devSocksProxy } : {}),
    reachable: true,
    latencyProxyMs: mode === 'ator' ? 5 : null,
    latencyDirectMs: 3,
    lastProbedAt: Date.now(),
    probeError: null,
    ts: Date.now(),
  });
});

try {
  await server.app.listen({ host: '127.0.0.1', port: 9400 });
} catch (err) {
  console.error('[Townhouse API] failed to listen on 127.0.0.1:9400:', err);
  process.exit(1);
}
console.log('[Townhouse API] listening on http://127.0.0.1:9400');
console.log(`[Townhouse API] connector admin: ${connectorAdminUrl}`);

let closing = false;
async function shutdown() {
  if (closing) return;
  closing = true;
  await server.close().catch((err) => {
    console.error('[Townhouse API] error during shutdown:', err);
  });
  process.exit(0);
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
