/**
 * Connector types for Townhouse (Story 21.3).
 *
 * Defines the runtime configuration shape for the standalone ILP connector,
 * peer entries, and admin API response types.
 */

import type { NodeType } from '../docker/types.js';

/**
 * A peer entry representing a child node connected to the connector via BTP.
 * Each active node becomes a child peer of the connector.
 */
export interface PeerEntry {
  /** Node type identifier (e.g., 'town', 'mill', 'dvm') */
  id: string;
  /** Relationship to connector — nodes are always children */
  relation: 'child';
  /** BTP WebSocket URL for Docker-internal communication */
  btpUrl: string;
  /** Asset code for ILP packets (e.g., 'USD') */
  assetCode: string;
  /** Asset scale (e.g., 6 for micro-units) */
  assetScale: number;
}

/**
 * Runtime configuration for the standalone ILP connector.
 * Generated by ConnectorConfigGenerator from TownhouseConfig.
 */
export interface ConnectorRuntimeConfig {
  /** Admin API listen port */
  adminPort: number;
  /** Base ILP address for this connector */
  ilpAddress: string;
  /** List of child peer entries (one per active node) */
  peers: PeerEntry[];
  /** Transport configuration */
  transport: {
    mode: 'ator' | 'direct';
    socksProxy?: string;
  };
}

// ── Admin API response types ──
//
// These mirror the connector's served shapes verbatim — see
// @toon-protocol/connector packages/connector/src/http/types.ts (HealthStatus)
// and packages/connector/src/http/admin-api.ts (AdminMetricsJsonResponse,
// /admin/peers handler). Drift here means dashboards break silently; the
// stub canary in `connector/contract-canary.test.ts` ratchets these shapes,
// and the running-image canary in `__integration__/connector-image-contract.test.ts`
// asserts the real connector still serves them.

/**
 * Response from GET /health on the connector's healthCheckPort.
 * Mirrors `HealthStatus` from `@toon-protocol/connector`.
 */
export interface HealthResponse {
  status: 'healthy' | 'unhealthy' | 'starting' | 'degraded';
  uptime: number;
  peersConnected: number;
  totalPeers: number;
  timestamp: string;
  nodeId?: string;
  version?: string;
}

/**
 * Per-peer ILP counter snapshot from GET /admin/metrics.json.
 * Mirrors `AdminMetricsJsonPeer` from `@toon-protocol/connector`.
 */
export interface MetricsPeerEntry {
  peerId: string;
  connected: boolean;
  packetsForwarded: number;
  packetsRejected: number;
  bytesSent: number;
  lastPacketAt: string | null;
}

/**
 * Response from GET /admin/metrics.json on the connector's adminApi port.
 * Mirrors `AdminMetricsJsonResponse` from `@toon-protocol/connector`.
 */
export interface MetricsResponse {
  uptimeSeconds: number;
  aggregate: {
    packetsForwarded: number;
    packetsRejected: number;
    bytesSent: number;
  };
  peers: MetricsPeerEntry[];
  timestamp: string;
}

/**
 * Peer entry from GET /admin/peers on the connector's adminApi port.
 * Mirrors the response of the connector's `router.get('/peers', …)` handler.
 * Note: per-peer packet counters live on /admin/metrics.json, not here.
 */
export interface PeerStatus {
  id: string;
  connected: boolean;
  ilpAddresses: string[];
  routeCount: number;
}

/**
 * Wrapper response from GET /admin/peers.
 * Mirrors the connector's `router.get('/peers')` JSON envelope.
 */
export interface PeersResponse {
  nodeId: string;
  peerCount: number;
  connectedCount: number;
  peers: PeerStatus[];
}

/** Node types that can be registered as peers */
export type { NodeType };
