/**
 * Connector types for Townhouse (Story 21.3).
 *
 * Defines the runtime configuration shape for the standalone ILP connector,
 * peer entries, and admin API response types.
 */

import type { NodeType } from '../docker/types.js';

/**
 * A peer entry representing a child node connected to the connector via BTP.
 * Each active node becomes a child peer of the connector.
 */
export interface PeerEntry {
  /** Node type identifier (e.g., 'town', 'mill', 'dvm') */
  id: string;
  /** Relationship to connector — nodes are always children */
  relation: 'child';
  /** BTP WebSocket URL for Docker-internal communication */
  btpUrl: string;
  /** Asset code for ILP packets (e.g., 'USD') */
  assetCode: string;
  /** Asset scale (e.g., 6 for micro-units) */
  assetScale: number;
}

/**
 * Runtime configuration for the standalone ILP connector.
 * Generated by ConnectorConfigGenerator from TownhouseConfig.
 */
export interface ConnectorRuntimeConfig {
  /** Admin API listen port */
  adminPort: number;
  /** Base ILP address for this connector */
  ilpAddress: string;
  /** List of child peer entries (one per active node) */
  peers: PeerEntry[];
  /** Transport configuration */
  transport: {
    mode: 'ator' | 'direct';
    socksProxy?: string;
  };
}

// ── Admin API response types ──

/** Response from GET /health */
export interface HealthResponse {
  status: 'healthy' | 'unhealthy';
  uptime: number;
}

/** Response from GET /metrics */
export interface MetricsResponse {
  packetsForwarded: number;
  packetsRejected: number;
  bytesSent: number;
}

/** Peer status from GET /peers */
export interface PeerStatus {
  id: string;
  connected: boolean;
  packetsForwarded: number;
}

/** Node types that can be registered as peers */
export type { NodeType };
